### ISSUE TITLE
New codes 

### ISSUE THREAD

**Issue by vkumar-ucd** [ken0225/RIS-Codes-Collection#5]
Hi Ken, 

Can you add the following repositories to the collection: 

1.  https://github.com/vkumar-ucd/EffectiveSecrecyRate
2. https://github.com/vkumar-ucd/IRS_MIMO_UnderlaySpectrumSharing
3. https://github.com/vkumar-ucd/SCABeamformingIRS

Thanks,
Vaibhav

**Comment by ken0225** [comment]
Dear Vaibhav,No problem, they will be added soon.Best regardsKen  从 Windows 版邮件发送 发件人: vkumar-ucd发送时间: 2023年2月3日 13:43收件人: ken0225/RIS-Codes-Collection抄送: Subscribed主题: [ken0225/RIS-Codes-Collection] New codes (Issue #5) Hi Ken,Can you add the following repositories to the collection:https://github.com/vkumar-ucd/EffectiveSecrecyRatehttps://github.com/vkumar-ucd/IRS_MIMO_UnderlaySpectrumSharinghttps://github.com/vkumar-ucd/SCABeamformingIRSThanks,Vaibhav—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by ken0225** [comment]
Dear Vaibhav, I just found that two of your works have already been added in the project (see [66] and [67]). I will add your latest work to the project. Best regards Ken 从 Windows 版邮件发送 发件人: vkumar-ucd发送时间: 2023年2月3日 13:43收件人: ken0225/RIS-Codes-Collection抄送: Subscribed主题: [ken0225/RIS-Codes-Collection] New codes (Issue #5) Hi Ken,Can you add the following repositories to the collection:https://github.com/vkumar-ucd/EffectiveSecrecyRatehttps://github.com/vkumar-ucd/IRS_MIMO_UnderlaySpectrumSharinghttps://github.com/vkumar-ucd/SCABeamformingIRSThanks,Vaibhav—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by ken0225** [comment]
Dear Vaibhav,
 
I just found that two of your works have already been added in the project (see [66] and [67]).
 
I will add your latest work, i.e., the 3rd one, to the project.
 
Best regards
 
Ken
